# -*- coding: utf-8 -*-
"""Aprior.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIZmLkcjZAb4Qm5H9kPrTkT24daRN0vp
"""

pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import apyori as apriori

from google.colab import files

uploaded = files.upload()

data = pd.read_csv('data.csv',header=None)

data.shape

records = []
for i in range (0,9836):
  records.append([str(data.values[i,j]) for j in range (0,33)])

association_rules = apriori(records , min_support = 0.50,min_confidence = 0.7, min_lift=3,min_length=2)
association_results = list(association_rules)

print(len(association_results))

print(association_results)